[general]
import = [
  "themes/tokyonight_night.toml",
]

[window]
startup_mode = "Fullscreen"

[font]
size = 14

[font.offset]
x = 0
y = 10

[font.glyph_offset]
y = 5

[font.normal]
style = "Regular"

[font.italic]
style = "Italic"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[cursor.style]
shape = "Beam"
blinking = "On"

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right",  action = "Paste" },
  { mouse = "Middle", mode = "~Vi", action = "PasteSelection" },
]

[keyboard]
bindings = [
  { key = "Return", mods = "Alt",                     action = "ToggleFullscreen" },
  { key = "Space",  mods = "Control", mode = "~Search",  action = "ToggleViMode" },
  { key = "J",      mods = "Control",                    action = "ScrollHalfPageDown" },
  { key = "J",      mods = "Shift",   mode = "Vi|~Search", action = "ScrollHalfPageDown" },
  { key = "K",      mods = "Control",                    action = "ScrollHalfPageUp" },
  { key = "K",      mods = "Shift",   mode = "Vi|~Search", action = "ScrollHalfPageUp" },
]
