[opener]
edit = [
  { run = 'zeditor "$@"', orphan = true, for = "unix" },
]
image = [
  { run = 'swayimg "$@"', orphan = true, for = "unix" },
]
pdf = [
  { run = 'sioyek "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
  # Folder
  { url = "*/", use = [ "edit", "open", "reveal" ] },
  # Text
  { mime = "text/*", use = [ "edit", "reveal" ] },
  # Image
  { mime = "image/*", use = [ "image", "reveal" ] },
  # Media
  { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
  # Code
  { mime = "application/{json,ndjson,javascript,wine-extension-ini}", use = [ "edit", "reveal" ] },
  { mime = "application/pdf", use = [ "pdf", "reveal" ] },
  # Fallback
  { url = "*", use = [ "open", "reveal" ] },
]
